export const currencies = [

  { country: 'Afghanistan', currency: 'Afghan afghani', code: 'AFN' },
  { country: 'Akrotiri and Dhekelia (UK)', currency: 'European euro', code: 'EUR' },
  { country: 'Aland Islands (Finland)', currency: 'European euro', code: 'EUR' },
  { country: 'Albania', currency: 'Albanian lek', code: 'ALL' },
  { country: 'Algeria', currency: 'Algerian dinar', code: 'DZD' },
  { country: 'American Samoa (USA)', currency: 'United States dollar', code: 'USD' },
  { country: 'Andorra', currency: 'European euro', code: 'EUR' },
  { country: 'Angola', currency: 'Angolan kwanza', code: 'AOA' },
  { country: 'Anguilla (UK)', currency: 'East Caribbean dollar', code: 'XCD' },
  { country: 'Antigua and Barbuda', currency: 'East Caribbean dollar', code: 'XCD' },
  { country: 'Argentina', currency: 'Argentine peso', code: 'ARS' },
  { country: 'Armenia', currency: 'Armenian dram', code: 'AMD' },
  { country: 'Aruba (Netherlands)', currency: 'Aruban florin', code: 'AWG' },
  { country: 'Ascension Island (UK)', currency: 'Saint Helena pound', code: 'SHP' },
  { country: 'Australia', currency: 'Australian dollar', code: 'AUD' },
  { country: 'Austria', currency: 'European euro', code: 'EUR' },
  { country: 'Azerbaijan', currency: 'Azerbaijan manat', code: 'AZN' },
  { country: 'Bahamas', currency: 'Bahamian dollar', code: 'BSD' },
  { country: 'Bahrain', currency: 'Bahraini dinar', code: 'BHD' },
  { country: 'Bangladesh', currency: 'Bangladeshi taka', code: 'BDT' },
  { country: 'Barbados', currency: 'Barbadian dollar', code: 'BBD' },
  { country: 'Belarus', currency: 'Belarusian ruble', code: 'BYN' },
  { country: 'Belgium', currency: 'European euro', code: 'EUR' },
  { country: 'Belize', currency: 'Belize dollar', code: 'BZD' },
  { country: 'Benin', currency: 'West African CFA franc', code: 'XOF' },
  { country: 'Bermuda (UK)', currency: 'Bermudian dollar', code: 'BMD' },
  { country: 'Bhutan', currency: 'Bhutanese ngultrum', code: 'BTN' },
  { country: 'Bolivia', currency: 'Bolivian boliviano', code: 'BOB' },
  { country: 'Bonaire (Netherlands)', currency: 'United States dollar', code: 'USD' },
  { country: 'Bosnia and Herzegovina', currency: 'Bosnia and Herzegovina convertible mark', code: 'BAM' },
  { country: 'Botswana', currency: 'Botswana pula', code: 'BWP' },
  { country: 'Brazil', currency: 'Brazilian real', code: 'BRL' },
  { country: 'British Indian Ocean Territory (UK)', currency: 'United States dollar', code: 'USD' },
  { country: 'British Virgin Islands (UK)', currency: 'United States dollar', code: 'USD' },
  { country: 'Brunei', currency: 'Brunei dollar', code: 'BND' },
  { country: 'Bulgaria', currency: 'Bulgarian lev', code: 'BGN' },
  { country: 'Burkina Faso', currency: 'West African CFA franc', code: 'XOF' },
  { country: 'Burundi', currency: 'Burundi franc', code: 'BIF' },
  { country: 'Cabo Verde', currency: 'Cape Verdean escudo', code: 'CVE' },
  { country: 'Cambodia', currency: 'Cambodian riel', code: 'KHR' },
  { country: 'Cameroon', currency: 'Central African CFA franc', code: 'XAF' },
  { country: 'Canada', currency: 'Canadian dollar', code: 'CAD' },
  { country: 'Caribbean Netherlands (Netherlands)', currency: 'United States dollar', code: 'USD' },
  { country: 'Cayman Islands (UK)', currency: 'Cayman Islands dollar', code: 'KYD' },
  { country: 'Central African Republic', currency: 'Central African CFA franc', code: 'XAF' },
  { country: 'Chad', currency: 'Central African CFA franc', code: 'XAF' },
  { country: 'Chatham Islands (New Zealand)', currency: 'New Zealand dollar', code: 'NZD' },
  { country: 'Chile', currency: 'Chilean peso', code: 'CLP' },
  { country: 'China', currency: 'Chinese Yuan Renminbi', code: 'CNY' },
  { country: 'Christmas Island (Australia)', currency: 'Australian dollar', code: 'AUD' },
  { country: 'Cocos (Keeling) Islands (Australia)', currency: 'Australian dollar', code: 'AUD' },
  { country: 'Colombia', currency: 'Colombian peso', code: 'COP' },
  { country: 'Comoros', currency: 'Comorian franc', code: 'KMF' },
  { country: 'Congo, Democratic Republic of the', currency: 'Congolese franc', code: 'CDF' },
  { country: 'Congo, Republic of the', currency: 'Central African CFA franc', code: 'XAF' },
  { country: 'Cook Islands (New Zealand)', currency: 'Cook Islands dollar', code: 'none' },
  { country: 'Costa Rica', currency: 'Costa Rican colon', code: 'CRC' },
  { country: 'Cote d\'Ivoire', currency: 'West African CFA franc', code: 'XOF' },
  { country: 'Croatia', currency: 'Croatian kuna', code: 'HRK' },
  { country: 'Cuba', currency: 'Cuban peso', code: 'CUP' },
  { country: 'Curacao (Netherlands)', currency: 'Netherlands Antillean guilder', code: 'ANG' },
  { country: 'Cyprus', currency: 'European euro', code: 'EUR' },
  { country: 'Czech Republic', currency: 'Czech koruna', code: 'CZK' },
  { country: 'Denmark', currency: 'Danish krone', code: 'DKK' },
  { country: 'Djibouti', currency: 'Djiboutian franc', code: 'DJF' },
  { country: 'Dominica', currency: 'East Caribbean dollar', code: 'XCD' },
  { country: 'Dominican Republic', currency: 'Dominican peso', code: 'DOP' },
  { country: 'Ecuador', currency: 'United States dollar', code: 'USD' },
  { country: 'Egypt', currency: 'Egyptian pound', code: 'EGP' },
  { country: 'El Salvador', currency: 'United States dollar', code: 'USD' },
  { country: 'Equatorial Guinea', currency: 'Central African CFA franc', code: 'XAF' },
  { country: 'Eritrea', currency: 'Eritrean nakfa', code: 'ERN' },
  { country: 'Estonia', currency: 'European euro', code: 'EUR' },
  { country: 'Ethiopia', currency: 'Ethiopian birr', code: 'ETB' },
  { country: 'Falkland Islands (UK)', currency: 'Falkland Islands pound', code: 'FKP' },
  { country: 'Faroe Islands (Denmark)', currency: 'Faroese krona', code: 'none' },
  { country: 'Fiji', currency: 'Fijian dollar', code: 'FJD' },
  { country: 'Finland', currency: 'European euro', code: 'EUR' },
  { country: 'France', currency: 'European euro', code: 'EUR' },
  { country: 'French Guiana (France)', currency: 'European euro', code: 'EUR' },
  { country: 'French Polynesia (France)', currency: 'CFP franc', code: 'XPF' },
  { country: 'Gabon', currency: 'Central African CFA franc', code: 'XAF' },
  { country: 'Gambia', currency: 'Gambian dalasi', code: 'GMD' },
  { country: 'Georgia', currency: 'Georgian lari', code: 'GEL' },
  { country: 'Germany', currency: 'European euro', code: 'EUR' },
  { country: 'Ghana', currency: 'Ghanaian cedi', code: 'GHS' },
  { country: 'Gibraltar (UK)', currency: 'Gibraltar pound', code: 'GIP' },
  { country: 'Greece', currency: 'European euro', code: 'EUR' },
  { country: 'Greenland (Denmark)', currency: 'Danish krone', code: 'DKK' },
  { country: 'Grenada', currency: 'East Caribbean dollar', code: 'XCD' },
  { country: 'Guadeloupe (France)', currency: 'European euro', code: 'EUR' },
  { country: 'Guam (USA)', currency: 'United States dollar', code: 'USD' },
  { country: 'Guatemala', currency: 'Guatemalan quetzal', code: 'GTQ' },
  { country: 'Guernsey (UK)', currency: 'Guernsey Pound', code: 'GGP' },
  { country: 'Guinea', currency: 'Guinean franc', code: 'GNF' },
  { country: 'Guinea-Bissau', currency: 'West African CFA franc', code: 'XOF' },
  { country: 'Guyana', currency: 'Guyanese dollar', code: 'GYD' },
  { country: 'Haiti', currency: 'Haitian gourde', code: 'HTG' },
  { country: 'Honduras', currency: 'Honduran lempira', code: 'HNL' },
  { country: 'Hong Kong (China)', currency: 'Hong Kong dollar', code: 'HKD' },
  { country: 'Hungary', currency: 'Hungarian forint', code: 'HUF' },
  { country: 'Iceland', currency: 'Icelandic krona', code: 'ISK' },
  { country: 'India', currency: 'Indian rupee', code: 'INR' },
  { country: 'Indonesia', currency: 'Indonesian rupiah', code: 'IDR' },
  { country: 'International Monetary Fund (IMF)', currency: 'SDR (Special Drawing Right)', code: 'XDR' },
  { country: 'Iran', currency: 'Iranian rial', code: 'IRR' },
  { country: 'Iraq', currency: 'Iraqi dinar', code: 'IQD' },
  { country: 'Ireland', currency: 'European euro', code: 'EUR' },
  { country: 'Isle of Man (UK)', currency: 'Manx pound', code: 'IMP' },
  { country: 'Israel', currency: 'Israeli new shekel', code: 'ILS' },
  { country: 'Italy', currency: 'European euro', code: 'EUR' },
  { country: 'Jamaica', currency: 'Jamaican dollar', code: 'JMD' },
  { country: 'Japan', currency: 'Japanese yen', code: 'JPY' },
  { country: 'Jersey (UK)', currency: 'Jersey pound', code: 'JEP' },
  { country: 'Jordan', currency: 'Jordanian dinar', code: 'JOD' },
  { country: 'Kazakhstan', currency: 'Kazakhstani tenge', code: 'KZT' },
  { country: 'Kenya', currency: 'Kenyan shilling', code: 'KES' },
  { country: 'Kiribati', currency: 'Australian dollar', code: 'AUD' },
  { country: 'Kosovo', currency: 'European euro', code: 'EUR' },
  { country: 'Kuwait', currency: 'Kuwaiti dinar', code: 'KWD' },
  { country: 'Kyrgyzstan', currency: 'Kyrgyzstani som', code: 'KGS' },
  { country: 'Laos', currency: 'Lao kip', code: 'LAK' },
  { country: 'Latvia', currency: 'European euro', code: 'EUR' },
  { country: 'Lebanon', currency: 'Lebanese pound', code: 'LBP' },
  { country: 'Lesotho', currency: 'Lesotho loti', code: 'LSL' },
  { country: 'Liberia', currency: 'Liberian dollar', code: 'LRD' },
  { country: 'Libya', currency: 'Libyan dinar', code: 'LYD' },
  { country: 'Liechtenstein', currency: 'Swiss franc', code: 'CHF' },
  { country: 'Lithuania', currency: 'European euro', code: 'EUR' },
  { country: 'Luxembourg', currency: 'European euro', code: 'EUR' },
  { country: 'Macau (China)', currency: 'Macanese pataca', code: 'MOP' },
  { country: 'Macedonia (FYROM)', currency: 'Macedonian denar', code: 'MKD' },
  { country: 'Madagascar', currency: 'Malagasy ariary', code: 'MGA' },
  { country: 'Malawi', currency: 'Malawian kwacha', code: 'MWK' },
  { country: 'Malaysia', currency: 'Malaysian ringgit', code: 'MYR' },
  { country: 'Maldives', currency: 'Maldivian rufiyaa', code: 'MVR' },
  { country: 'Mali', currency: 'West African CFA franc', code: 'XOF' },
  { country: 'Malta', currency: 'European euro', code: 'EUR' },
  { country: 'Marshall Islands', currency: 'United States dollar', code: 'USD' },
  { country: 'Martinique (France)', currency: 'European euro', code: 'EUR' },
  { country: 'Mauritania', currency: 'Mauritanian ouguiya', code: 'MRU' },
  { country: 'Mauritius', currency: 'Mauritian rupee', code: 'MUR' },
  { country: 'Mayotte (France)', currency: 'European euro', code: 'EUR' },
  { country: 'Mexico', currency: 'Mexican peso', code: 'MXN' },
  { country: 'Micronesia', currency: 'United States dollar', code: 'USD' },
  { country: 'Moldova', currency: 'Moldovan leu', code: 'MDL' },
  { country: 'Monaco', currency: 'European euro', code: 'EUR' },
  { country: 'Mongolia', currency: 'Mongolian tugrik', code: 'MNT' },
  { country: 'Montenegro', currency: 'European euro', code: 'EUR' },
  { country: 'Montserrat (UK)', currency: 'East Caribbean dollar', code: 'XCD' },
  { country: 'Morocco', currency: 'Moroccan dirham', code: 'MAD' },
  { country: 'Mozambique', currency: 'Mozambican metical', code: 'MZN' },
  { country: 'Myanmar (Burma)', currency: 'Myanmar kyat', code: 'MMK' },
  { country: 'Namibia', currency: 'Namibian dollar', code: 'NAD' },
  { country: 'Nauru', currency: 'Australian dollar', code: 'AUD' },
  { country: 'Nepal', currency: 'Nepalese rupee', code: 'NPR' },
  { country: 'Netherlands', currency: 'European euro', code: 'EUR' },
  { country: 'New Caledonia (France)', currency: 'CFP franc', code: 'XPF' },
  { country: 'New Zealand', currency: 'New Zealand dollar', code: 'NZD' },
  { country: 'Nicaragua', currency: 'Nicaraguan cordoba', code: 'NIO' },
  { country: 'Niger', currency: 'West African CFA franc', code: 'XOF' },
  { country: 'Nigeria', currency: 'Nigerian naira', code: 'NGN' },
  { country: 'Niue (New Zealand)', currency: 'New Zealand dollar', code: 'NZD' },
  { country: 'Norfolk Island (Australia)', currency: 'Australian dollar', code: 'AUD' },
  { country: 'Northern Mariana Islands (USA)', currency: 'United States dollar', code: 'USD' },
  { country: 'North Korea', currency: 'North Korean won', code: 'KPW' },
  { country: 'Norway', currency: 'Norwegian krone', code: 'NOK' },
  { country: 'Oman', currency: 'Omani rial', code: 'OMR' },
  { country: 'Pakistan', currency: 'Pakistani rupee', code: 'PKR' },
  { country: 'Palau', currency: 'United States dollar', code: 'USD' },
  { country: 'Palestine', currency: 'Israeli new shekel', code: 'ILS' },
  { country: 'Panama', currency: 'United States dollar', code: 'USD' },
  { country: 'Papua New Guinea', currency: 'Papua New Guinean kina', code: 'PGK' },
  { country: 'Paraguay', currency: 'Paraguayan guarani', code: 'PYG' },
  { country: 'Peru', currency: 'Peruvian sol', code: 'PEN' },
  { country: 'Philippines', currency: 'Philippine peso', code: 'PHP' },
  { country: 'Pitcairn Islands (UK)', currency: 'New Zealand dollar', code: 'NZD' },
  { country: 'Poland', currency: 'Polish zloty', code: 'PLN' },
  { country: 'Portugal', currency: 'European euro', code: 'EUR' },
  { country: 'Puerto Rico (USA)', currency: 'United States dollar', code: 'USD' },
  { country: 'Qatar', currency: 'Qatari riyal', code: 'QAR' },
  { country: 'Reunion (France)', currency: 'European euro', code: 'EUR' },
  { country: 'Romania', currency: 'Romanian leu', code: 'RON' },
  { country: 'Russia', currency: 'Russian ruble', code: 'RUB' },
  { country: 'Rwanda', currency: 'Rwandan franc', code: 'RWF' },
  { country: 'Saba (Netherlands)', currency: 'United States dollar', code: 'USD' },
  { country: 'Saint Barthelemy (France)', currency: 'European euro', code: 'EUR' },
  { country: 'Saint Helena (UK)', currency: 'Saint Helena pound', code: 'SHP' },
  { country: 'Saint Kitts and Nevis', currency: 'East Caribbean dollar', code: 'XCD' },
  { country: 'Saint Lucia', currency: 'East Caribbean dollar', code: 'XCD' },
  { country: 'Saint Martin (France)', currency: 'European euro', code: 'EUR' },
  { country: 'Saint Pierre and Miquelon (France)', currency: 'European euro', code: 'EUR' },
  { country: 'Saint Vincent and the Grenadines', currency: 'East Caribbean dollar', code: 'XCD' },
  { country: 'Samoa', currency: 'Samoan tala', code: 'WST' },
  { country: 'San Marino', currency: 'European euro', code: 'EUR' },
  { country: 'Sao Tome and Principe', currency: 'Sao Tome and Principe dobra', code: 'STN' },
  { country: 'Saudi Arabia', currency: 'Saudi Arabian riyal', code: 'SAR' },
  { country: 'Senegal', currency: 'West African CFA franc', code: 'XOF' },
  { country: 'Serbia', currency: 'Serbian dinar', code: 'RSD' },
  { country: 'Seychelles', currency: 'Seychellois rupee', code: 'SCR' },
  { country: 'Sierra Leone', currency: 'Sierra Leonean leone', code: 'SLL' },
  { country: 'Singapore', currency: 'Singapore dollar', code: 'SGD' },
  { country: 'Sint Eustatius (Netherlands)', currency: 'United States dollar', code: 'USD' },
  { country: 'Sint Maarten (Netherlands)', currency: 'Netherlands Antillean guilder', code: 'ANG' },
  { country: 'Slovakia', currency: 'European euro', code: 'EUR' },
  { country: 'Slovenia', currency: 'European euro', code: 'EUR' },
  { country: 'Solomon Islands', currency: 'Solomon Islands dollar', code: 'SBD' },
  { country: 'Somalia', currency: 'Somali shilling', code: 'SOS' },
  { country: 'South Africa', currency: 'South African rand', code: 'ZAR' },
  { country: 'South Georgia Island (UK)', currency: 'Pound sterling', code: 'GBP' },
  { country: 'South Korea', currency: 'South Korean won', code: 'KRW' },
  { country: 'South Sudan', currency: 'South Sudanese pound', code: 'SSP' },
  { country: 'Spain', currency: 'European euro', code: 'EUR' },
  { country: 'Sri Lanka', currency: 'Sri Lankan rupee', code: 'LKR' },
  { country: 'Sudan', currency: 'Sudanese pound', code: 'SDG' },
  { country: 'Suriname', currency: 'Surinamese dollar', code: 'SRD' },
  { country: 'Svalbard and Jan Mayen (Norway)', currency: 'Norwegian krone', code: 'NOK' },
  { country: 'Swaziland', currency: 'Swazi lilangeni', code: 'SZL' },
  { country: 'Sweden', currency: 'Swedish krona', code: 'SEK' },
  { country: 'Switzerland', currency: 'Swiss franc', code: 'CHF' },
  { country: 'Syria', currency: 'Syrian pound', code: 'SYP' },
  { country: 'Taiwan', currency: 'New Taiwan dollar', code: 'TWD' },
  { country: 'Tajikistan', currency: 'Tajikistani somoni', code: 'TJS' },
  { country: 'Tanzania', currency: 'Tanzanian shilling', code: 'TZS' },
  { country: 'Thailand', currency: 'Thai baht', code: 'THB' },
  { country: 'Timor-Leste', currency: 'United States dollar', code: 'USD' },
  { country: 'Togo', currency: 'West African CFA franc', code: 'XOF' },
  { country: 'Tokelau (New Zealand)', currency: 'New Zealand dollar', code: 'NZD' },
  { country: 'Tonga', currency: 'Tongan pa’anga', code: 'TOP' },
  { country: 'Trinidad and Tobago', currency: 'Trinidad and Tobago dollar', code: 'TTD' },
  { country: 'Tristan da Cunha (UK)', currency: 'Pound sterling', code: 'GBP' },
  { country: 'Tunisia', currency: 'Tunisian dinar', code: 'TND' },
  { country: 'Turkey', currency: 'Turkish lira', code: 'TRY' },
  { country: 'Turkmenistan', currency: 'Turkmen manat', code: 'TMT' },
  { country: 'Turks and Caicos Islands (UK)', currency: 'United States dollar', code: 'USD' },
  { country: 'Tuvalu', currency: 'Australian dollar', code: 'AUD' },
  { country: 'Uganda', currency: 'Ugandan shilling', code: 'UGX' },
  { country: 'Ukraine', currency: 'Ukrainian hryvnia', code: 'UAH' },
  { country: 'United Arab Emirates', currency: 'UAE dirham', code: 'AED' },
  { country: 'United Kingdom', currency: 'Pound sterling', code: 'GBP' },
  { country: 'United States of America', currency: 'United States dollar', code: 'USD' },
  { country: 'Uruguay', currency: 'Uruguayan peso', code: 'UYU' },
  { country: 'US Virgin Islands (USA)', currency: 'United States dollar', code: 'USD' },
  { country: 'Uzbekistan', currency: 'Uzbekistani som', code: 'UZS' },
  { country: 'Vanuatu', currency: 'Vanuatu vatu', code: 'VUV' },
  { country: 'Vatican City (Holy See)', currency: 'European euro', code: 'EUR' },
  { country: 'Venezuela', currency: 'Venezuelan bolivar', code: 'VEF' },
  { country: 'Vietnam', currency: 'Vietnamese dong', code: 'VND' },
  { country: 'Wake Island (USA)', currency: 'United States dollar', code: 'USD' },
  { country: 'Wallis and Futuna (France)', currency: 'CFP franc', code: 'XPF' },
  { country: 'Yemen', currency: 'Yemeni rial', code: 'YER' },
  { country: 'Zambia', currency: 'Zambian kwacha', code: 'ZMW' },
  { country: 'Zimbabwe', currency: 'United States dollar', code: 'USD' }

];
