FROM ubuntu:16.04

RUN apt-get -qq update
RUN apt-get install locales

# install curl
RUN apt-get install -y curl

# download node.js
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -

# install node.js
RUN apt-get install -y nodejs

# ensure npm packages can build
RUN apt-get install -y build-essential
RUN apt-get install -y git-core

# install graphviz
RUN apt-get install -y graphviz
RUN apt-get install -y python3-pip
RUN pip3 install graphviz

# install chromium browser for karma test runner
RUN apt-get install -y chromium-browser

# set environment variable for chromium browser
ENV CHROME_BIN=/usr/bin/chromium

COPY . usr/src/app
WORKDIR /usr/src/app

# install app dependencies, compile server and build the angular client
RUN npm install

# run unit tests for Angular client
RUN npm run test:ci

# run end-to-end tests for Angular client
RUN npm run e2e

# run tests for backend RESTful API
RUN npm run testbe
