export class VatNumber {
  austria           : boolean;
  belgium           : boolean;
  bulgaria          : boolean;
  hungary           : boolean;
  netherlands       : boolean;
  cyprus            : boolean;
  czechRepublic     : boolean;
  germany           : boolean;
  denmark           : boolean;
  slovakia          : boolean;
  estonia           : boolean;
  greece            : boolean;
  ireland           : boolean;
  poland            : boolean;
  spain             : boolean;
  italy             : boolean;
  portugal          : boolean;
  finland           : boolean;
  lithuania         : boolean;
  romania           : boolean;
  france            : boolean;
  luxembourg        : boolean;
  southAfrica       : boolean;
  unitedKingdom     : boolean;
  latvia            : boolean;
  sweden            : boolean;
  croatia           : boolean;
  malta             : boolean;
  slovenia          : boolean;
  countryCode       : string;
  groupingCharacters: string;
}
