currency_to_code = {

	'Swazi lilangeni'                        : 'SZL',
	'Tunisian dinar'                         : 'TND',
	'Lao kip'                                : 'LAK',
	'Trinidad and Tobago dollar'             : 'TTD',
	'Iranian rial'                           : 'IRR',
	'Namibian dollar'                        : 'NAD',
	'Lebanese pound'                         : 'LBP',
	'Bhutanese ngultrum'                     : 'BTN',
	'Canadian dollar'                        : 'CAD',
	'Manx pound'                             : 'IMP',
	'Papua New Guinean kina'                 : 'PGK',
	'Haitian gourde'                         : 'HTG',
	'Malawian kwacha'                        : 'MWK',
	'Syrian pound'                           : 'SYP',
	'Mauritanian ouguiya'                    : 'MRU',
	'Malaysian ringgit'                      : 'MYR',
	'Guatemalan quetzal'                     : 'GTQ',
	'Ethiopian birr'                         : 'ETB',
	'Barbadian dollar'                       : 'BBD',
	'Macedonian denar'                       : 'MKD',
	'Norwegian krone'                        : 'NOK',
	'Fijian dollar'                          : 'FJD',
	'Egyptian pound'                         : 'EGP',
	'Tongan pa’anga'                         : 'TOP',
	'Dominican peso'                         : 'DOP',
	'Nicaraguan cordoba'                     : 'NIO',
	'New Taiwan dollar'                      : 'TWD',
	'Czech koruna'                           : 'CZK',
	'Jordanian dinar'                        : 'JOD',
	'Turkish lira'                           : 'TRY',
	'Qatari riyal'                           : 'QAR',
	'Armenian dram'                          : 'AMD',
	'Belize dollar'                          : 'BZD',
	'Macanese pataca'                        : 'MOP',
	'Chinese Yuan Renminbi'                  : 'CNY',
	'Myanmar kyat'                           : 'MMK',
	'Bulgarian lev'                          : 'BGN',
	'Peruvian sol'                           : 'PEN',
	'SDR (Special Drawing Right)'            : 'XDR',
	'Russian ruble'                          : 'RUB',
	'Saint Helena pound'                     : 'SHP',
	'Mozambican metical'                     : 'MZN',
	'Pound sterling'                         : 'GBP',
	'Paraguayan guarani'                     : 'PYG',
	'Sri Lankan rupee'                       : 'LKR',
	'Zambian kwacha'                         : 'ZMW',
	'Tajikistani somoni'                     : 'TJS',
	'United States dollar'                   : 'USD',
	'Sao Tome and Principe dobra'            : 'STN',
	'Serbian dinar'                          : 'RSD',
	'Botswana pula'                          : 'BWP',
	'Sudanese pound'                         : 'SDG',
	'Argentine peso'                         : 'ARS',
	'Mauritian rupee'                        : 'MUR',
	'Cape Verdean escudo'                    : 'CVE',
	'Sierra Leonean leone'                   : 'SLL',
	'Philippine peso'                        : 'PHP',
	'Malagasy ariary'                        : 'MGA',
	'Faroese krona'                          : 'none',
	'Maldivian rufiyaa'                      : 'MVR',
	'Eritrean nakfa'                         : 'ERN',
	'Gibraltar pound'                        : 'GIP',
	'Australian dollar'                      : 'AUD',
	'Netherlands Antillean guilder'          : 'ANG',
	'Cook Islands dollar'                    : 'none',
	'Uruguayan peso'                         : 'UYU',
	'Colombian peso'                         : 'COP',
	'Cayman Islands dollar'                  : 'KYD',
	'Singapore dollar'                       : 'SGD',
	'Bolivian boliviano'                     : 'BOB',
	'Guyanese dollar'                        : 'GYD',
	'Brunei dollar'                          : 'BND',
	'Belarusian ruble'                       : 'BYN',
	'Swiss franc'                            : 'CHF',
	'Yemeni rial'                            : 'YER',
	'South African rand'                     : 'ZAR',
	'Djiboutian franc'                       : 'DJF',
	'Rwandan franc'                          : 'RWF',
	'Seychellois rupee'                      : 'SCR',
	'Polish zloty'                           : 'PLN',
	'Omani rial'                             : 'OMR',
	'Kyrgyzstani som'                        : 'KGS',
	'Bermudian dollar'                       : 'BMD',
	'Costa Rican colon'                      : 'CRC',
	'Saudi Arabian riyal'                    : 'SAR',
	'South Sudanese pound'                   : 'SSP',
	'Kuwaiti dinar'                          : 'KWD',
	'Solomon Islands dollar'                 : 'SBD',
	'Icelandic krona'                        : 'ISK',
	'Nigerian naira'                         : 'NGN',
	'UAE dirham'                             : 'AED',
	'Jamaican dollar'                        : 'JMD',
	'Angolan kwanza'                         : 'AOA',
	'Swedish krona'                          : 'SEK',
	'Brazilian real'                         : 'BRL',
	'Chilean peso'                           : 'CLP',
	'Thai baht'                              : 'THB',
	'Hong Kong dollar'                       : 'HKD',
	'Hungarian forint'                       : 'HUF',
	'Aruban florin'                          : 'AWG',
	'Kazakhstani tenge'                      : 'KZT',
	'Moroccan dirham'                        : 'MAD',
	'Jersey pound'                           : 'JEP',
	'Burundi franc'                          : 'BIF',
	'Croatian kuna'                          : 'HRK',
	'Samoan tala'                            : 'WST',
	'Georgian lari'                          : 'GEL',
	'Algerian dinar'                         : 'DZD',
	'Iraqi dinar'                            : 'IQD',
	'CFP franc'                              : 'XPF',
	'North Korean won'                       : 'KPW',
	'Guernsey Pound'                         : 'GGP',
	'East Caribbean dollar'                  : 'XCD',
	'Cuban peso'                             : 'CUP',
	'Pakistani rupee'                        : 'PKR',
	'Bangladeshi taka'                       : 'BDT',
	'Liberian dollar'                        : 'LRD',
	'West African CFA franc'                 : 'XOF',
	'Indonesian rupiah'                      : 'IDR',
	'Cambodian riel'                         : 'KHR',
	'Central African CFA franc'              : 'XAF',
	'Vanuatu vatu'                           : 'VUV',
	'Tanzanian shilling'                     : 'TZS',
	'Japanese yen'                           : 'JPY',
	'Turkmen manat'                          : 'TMT',
	'Romanian leu'                           : 'RON',
	'European euro'                          : 'EUR',
	'Mexican peso'                           : 'MXN',
	'Venezuelan bolivar'                     : 'VEF',
	'Afghan afghani'                         : 'AFN',
	'New Zealand dollar'                     : 'NZD',
	'Ugandan shilling'                       : 'UGX',
	'Lesotho loti'                           : 'LSL',
	'Kenyan shilling'                        : 'KES',
	'Moldovan leu'                           : 'MDL',
	'Guinean franc'                          : 'GNF',
	'Honduran lempira'                       : 'HNL',
	'Congolese franc'                        : 'CDF',
	'Uzbekistani som'                        : 'UZS',
	'Mongolian tugrik'                       : 'MNT',
	'Indian rupee'                           : 'INR',
	'Ukrainian hryvnia'                      : 'UAH',
	'Comorian franc'                         : 'KMF',
	'Danish krone'                           : 'DKK',
	'Bahraini dinar'                         : 'BHD',
	'Bahamian dollar'                        : 'BSD',
	'Gambian dalasi'                         : 'GMD',
	'Ghanaian cedi'                          : 'GHS',
	'Azerbaijan manat'                       : 'AZN',
	'Somali shilling'                        : 'SOS',
	'Vietnamese dong'                        : 'VND',
	'Bosnia and Herzegovina convertible mark': 'BAM',
	'Israeli new shekel'                     : 'ILS',
	'South Korean won'                       : 'KRW',
	'Falkland Islands pound'                 : 'FKP',
	'Surinamese dollar'                      : 'SRD',
	'Nepalese rupee'                         : 'NPR',
	'Libyan dinar'                           : 'LYD',
	'Albanian lek'                           : 'ALL',

}