from regy.samples_and_semantics.mapper import meta_characters
from regy.samples_and_semantics.mapper.map_marked_text import MapMarkedText
from regy.samples_and_semantics.mapper.map_numbers import MapNumbers