class UrlInfo:

    def __init__(self, info):
        self.schemes                    = info['schemes']
        self.port_numbers               = info['portNumbers']
        self.spec_optional_port_numbers = info['specOptionalPortNumbers']
        self.spec_required_port_numbers = info['specRequiredPortNumbers']
        self.username                   = info['username']
        self.spec_usernames             = info['specUserNames']
        self.password                   = info['password']
        self.domain_name                = info['domainName']
        self.spec_domain_names          = info['specDomainNames']
        self.specific_tld               = info['specificTld']
        self.subdomain_on_spec_domain   = info['subdomainOnSpecDomain']
        self.folders                    = info['folders']
        self.min_folder_depth           = info['minFolderDepth']
        self.max_folder_depth           = info['maxFolderDepth']
        self.spec_folders_only          = info['specFoldersOnly']
        self.spec_paths_only            = info['specPathsOnly']
        self.file_names                 = info['fileNames']
        self.spec_extensions            = info['specExtensions']
        self.spec_file_names            = info['specFileNames']
        self.optional_file_names        = info['optionalFileNames']
        self.parameters                 = info['parameters']
        self.spec_parameters            = info['specParameters']
